name: Commitlint

on:
  push:
    branches:
      - '**'

jobs:
  commitlint:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Fix permissions for Node binaries
        run: chmod +x ./node_modules/.bin/*

      - name: Determine commit range
        id: commit_range
        run: |
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            echo "FROM=$(git rev-parse HEAD^ || echo HEAD)" >> $GITHUB_ENV
          else
            echo "FROM=${{ github.event.before }}" >> $GITHUB_ENV
          fi
          echo "TO=${{ github.sha }}" >> $GITHUB_ENV
          
      - name: Lint commits
        run: npx commitlint --verbose --from=${{ env.FROM }} --to=${{ env.TO }}
        
      - name: Run dotnet format for Specific Solution
        run: dotnet format ./DotNet/TestFormatProject/TestFormatProject.sln --verify-no-changes
