name: Commitlint

on:
  push:
    branches:
      - '**' # Run on commits to all branches

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Commitlint
        run: npm install --save-dev @commitlint/{config-conventional,cli}

      - name: Lint commits
        run: |
          git log --format=%H ${{ github.event.before }}..${{ github.sha }} | xargs -I {} npx commitlint --verbose --commit {}
