name: Commitlint

permissions:
  contents: write

on:
  push:
    branches:
      - '**'

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Commitlint
        run: npm install --save-dev @commitlint/{config-conventional,cli}

      - name: Lint commits in the push
        run: |
          git log --format=%H | xargs -I {} npx commitlint --verbose --commit {}
