name: Commitlint

on:
  push:
    branches:
      - '**'

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Commitlint
        run: npm install --save-dev @commitlint/{config-conventional,cli}

      - name: Get commit range
        id: commits
        run: |
          echo "FROM=$(git rev-parse HEAD~1 || echo HEAD)" >> $GITHUB_ENV
          echo "TO=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Lint commits
        run: npx commitlint --from=${{ env.FROM }} --to=${{ env.TO }}
